FROM python
WORKDIR /app
COPY requirements.txt ./requirements.txt
# RUN pip3 install -r requirements.txt
RUN pip install --upgrade pip setuptools wheel \
    && pip install -r requirements.txt \
    && rm -rf /root/.cache/pip
EXPOSE 8501
COPY . /app
ENTRYPOINT [ "streamlit","run"]
CMD [ "bddinventory.py" ]